name = "bam-scam-tracker"
compatibility_date = "2026-06-01"

[[d1_databases]]
binding = "DB"
database_name = "bam_scam_tracker"
database_id = "a97d4459-0ab1-4820-8199-4a7270e8285e"
migrations_dir = "migrations"


[[kv_namespaces]]
binding = "SESSION"
id = "85389f063f71431fb54d3d7197af362a"

[vars]
PUBLIC_SITE_NAME = "BAM Scam Tracker"
PUBLIC_DONATION_URL = "https://buymeacoffee.com/bam.scam.tracker"
ADMIN_TOKEN = ""
ENABLE_AI_INGESTION = "false"
AI_MAX_SOURCES_PER_RUN = "2"
AI_SOURCE_CHAR_LIMIT = "4000"
OPENAI_MODEL = "gpt-4.1-mini"
