name = "bam-scam-tracker-ingest"
main = "workers/scheduled-ingest.ts"
compatibility_date = "2026-06-01"

[[d1_databases]]
binding = "DB"
database_name = "bam_scam_tracker"
database_id = "a97d4459-0ab1-4820-8199-4a7270e8285e"
migrations_dir = "migrations"


[[kv_namespaces]]
binding = "SESSION"
id = "85389f063f71431fb54d3d7197af362a"

[vars]
OPENAI_MODEL = "gpt-4.1-mini"

[triggers]
crons = ["0 */6 * * *"]
